//! OpenGL 2.1 compatibility-profile bindings generated by `build.rs`.
//!
//! The fixed-function entry points (`Begin`, `MatrixMode`, `DrawPixels`, ...) are
//! part of the compatibility profile, so they are generated here instead of being
//! linked against a platform-specific OpenGL library.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/gl_bindings.rs"));
